name: Deploy intership
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Instal deps
        run: npm install
      - name: Run deploy
        run: npm run dev
